### ISSUE TITLE
Get access to existing site & infrastructure

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#18]
We need the keys!
- [ ] Obtain admin credentials for existing site Drupal
- [ ] Obtain access to Google sheets "database"
- [ ] Define any other technical assets for SOL

**Comment by biodavis** [comment]
I will be asking Eleanor questions, so I can follow up with her brother to tel us how to access.  Also, this brother is supposed to be at upcoming meeting.

**Comment by dviramontes** [comment]
just email Tony from Denver Open Media, the org that built the first version of the site.
I invited them to our next meeting. Hopefully they can make it.

**Comment by hasuf** [comment]
@dviramontes  and @underhilllabs  have the keys to the castle.
