### ISSUE TITLE
Take existing site and make mobile-ready

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#2]
This should probably be a milestone rather than an individual issue, but here goes:

Acceptance criteria:
- [ ] Simpler navigation for touch devices
- [ ] Quick access to File a Report on small screen
- [ ] Quick access to Find Resources
- [ ] Quick access to About SOL
- [ ] Ability to finish filing a report from device
- [ ] Ability to find nearby resources (geolocation)
- [ ] Ability to navigate additional SOL information from device

blocked by #1

**Comment by swdgit** [comment]
issue #4 shows the user definition of Mobile Ready.
The Simple view is larger, basic, buttons that correspond with the tab navigation on the site.
