### ISSUE TITLE
Reporting web form or chat

### ISSUE THREAD

**Issue by switzersc** [codefordenver/sol-cavp#28]

**Comment by dkoloditch** [comment]
free open source website chat client: https://conversejs.org/

**Comment by swdgit** [comment]
I'd add a requirement here that any chat/form needs to be secure. https or equivalent with a secure, conus based datacenter, to ensure safety.

**Comment by vallejoj** [comment]
I found a pretty inexpensive chat called Olark that is super simple to use and pretty cheap as well. I just installed it to my Drupal site in 5 minutes. 

Edit (Joseph): Olark pricing plan: https://www.olark.com/pricing

**Comment by dkoloditch** [comment]
Resources:
- https://www.olark.com/help/drupal
- Converse.js Drupal module: https://www.drupal.org/project/conversejs
- DrupalChat module: https://www.drupal.org/project/drupalchat

**Comment by dkoloditch** [comment]
Converse.js Drupal module: https://www.drupal.org/project/conversejs

**Comment by hasuf** [comment]
Not working on this for this project.
