### ISSUE TITLE
Streamline current reporting intake

### ISSUE THREAD

**Issue by switzersc** [codefordenver/sol-cavp#32]

**Comment by joshuaboy7** [comment]
Data reporting could be done in two different ways, both are easy to implement and manage, and both are hosted somewhere else. The choice would come down to how the data would best be used.
1. Google Form tied to Google Spreadsheet.
2. Ushahidi or Crowdmap http://www.ushahidi.com/

**Comment by hasuf** [comment]
Calling this done. Going with Google Spreadsheet
