### ISSUE TITLE
Define what mobile-ready means

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#4]
What data needs to be made mobile-ready?

**Comment by swdgit** [comment]
Discussed with Lynne and Eleanor what this means for them.
A) The web-site is going to be re-factored a bit and will line up with the Mobile definition pretty easily.
B) the images attached give a high level overview of what Mobile means, simple buttons/text, vs a whole site re-design.

Think larger, simple buttons that are reflective of the web-site tabs.

The main.jpg image is based on larger buttons that match up with tabs to be or will be available on the updated web-site.

![image](https://cloud.githubusercontent.com/assets/6437458/6364600/ee277f8a-bc65-11e4-926e-df106989d64a.png)

The Resources button would have a short list of items that would also be found on the full web-site Resources tab.

![resources](https://cloud.githubusercontent.com/assets/6437458/6364602/f54dea24-bc65-11e4-89d9-a714f49abfdf.jpg)

**Comment by drosile** [comment]
relates to #2

**Comment by dviramontes** [comment]
moved to backlog since out of scope
