### ISSUE TITLE
Safety Plan

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#53]
Data required:
- Decision Tree
- Doable without support from volunteers
- Next actions
- Type of violence

Information returned
- Shelter options
- Legal options
- What to take when you leave

(Create an HTML container for resources?)

**Comment by karenderrickdavis** [comment]
Safety plan Tool

Should:  volunteer/user-customizable (maintainable by volunteers)

Diagramming tool →  ?? (XML?)  →   code/hosted or embeddable app → generate artifact; pdf? url? webpage?

Decision tree opensource

Yahoo Pipes
Freemind
Research current options
build v. use?

Does it generate a form?

People make their own website with a decision tree.

prototype with gDraw or other free tool

need some initial model of existing tree

**Comment by dkoloditch** [comment]
this might help serve as a starting point: http://www.domesticviolence.org/personalized-safety-plan/

**Comment by dkoloditch** [comment]
some helpful references/resources:
- http://www.domesticviolence.org/personalized-safety-plan/
- http://www.gojs.net/latest/samples/decisionTree.html
- http://www.dbi.io/uk/blog/38-tools-for-beautiful-data-visualisations/
- https://code.google.com/p/interactive-decision-tree/
- http://philau.willbowman.com/2012/digitalInnovation/DevelopmentReferences/LIBS/d3JS/examples/tree/tree-interactive.html
- https://www.drupal.org/project/decision_tree
- https://www.drupal.org/search/site/decision%20tree?f%5B0%5D=ss_meta_type%3Amodule
- d3 dendogram: http://bl.ocks.org/mbostock/4063570
- http://www.daviddurman.com/automatic-graph-layout-with-jointjs-and-dagre.html
- building a decision tree in d3.js: http://blog.pixelingene.com/2011/07/building-a-tree-diagram-in-d3-js/
- bl.ocks.org
- Google chart treemap: https://google-developers.appspot.com/chart/interactive/docs/gallery/treemap

**Comment by dkoloditch** [comment]
see #51

**Comment by karenderrickdavis** [comment]
Not applicable, anymore.
