### ISSUE TITLE
See how Drupal can embed I-frame and compare that to the plug in for Google Docs. 

### ISSUE THREAD

**Issue by vallejoj** [codefordenver/sol-cavp#57]

**Comment by vallejoj** [comment]
I was not able to get the module or a simple I-frame to work. There is not that much documentation on the matter and for everything I tried I would receive errors or it would simply not work.  I think David's idea of creating a way of seeing documents ourselves would be much easier for the group.

**Comment by dviramontes** [comment]
@vallejoj thanks for the update,  we came up with another possible solution for this,  checkout the meeting notes on flowdock, see you next time :)
moving this to done
