### ISSUE TITLE
look into db (ie, non-spreadsheet) datastore solutions

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#64]

**Comment by dviramontes** [comment]
I'll ask @brettevans to see if he has an update for us on this but i think we need to find a solution for this very soon, this is a crucial part of the intake process

**Comment by haydenevans** [comment]
Brett found a couple spreadsheet-to-S3 libraries as well as the Google Apps script to Google's MySQL service. He'll talk more about these options tonight.

**Comment by dviramontes** [comment]
awesome!

**Comment by brettevans** [comment]
Could be solved with Google Spreadsheets "Version History"

**Comment by karenderrickdavis** [comment]
Not relevant now that we are using Google spreadsheets.
