### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#76]
For the abbreviated survivor form (#74), show CAPTCHA to reduce the garbage that gets entered.

**Comment by hasuf** [comment]
Info to the single-click, "No CAPTCHA reCAPTCHA" as discussed on Monday: http://googleonlinesecurity.blogspot.com/2014/12/are-you-robot-introducing-no-captcha.html

API Docs here: https://developers.google.com/recaptcha/

Note: language can be specified. Should be considered in conjunction with #67

**Comment by dviramontes** [comment]
Good point. Thanks @hasuf !

**Comment by karenderrickdavis** [comment]
CAVP wants CAPTCHA.

**Comment by brettevans** [comment]
A CAPTCHA could be implemented by creating a simple multiple choice question with shuffled option order under 'Advanced Settings' on the question.

**Comment by hasuf** [comment]
Calling this one done after review on 4/20
