### ISSUE TITLE
Define data management

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#8]
3 original questions:
1) Cavp collects what data and for what purpose (and what format)
2) cavp reports (passses on) data to whom and what data and what format
3) Survivor reports :  what data in which formats and for what purpose.

Acceptance criteria:
- [x] [Survivor reports] Complete #30
- [x] [National reporting] Complete #29
- [x] [Additional data collection] Define data collected
- [x] [Additional data collection] Define format of data collected
- [x] [Additional data collection] Define purpose of data collected

**Comment by biodavis** [comment]
Brian and Josh working on this.

3 original questions:  
1) Cavp collects what data and for what purpose (and what format)
2) cavp reports (passses on) data to whom and what data and what format
3) Survivor reports :  what data in which formats and for what purpose.

types of data (separate):  
1) website
2) survivor intake data
For survivor intake data:
They now manage a google spreadsheet that has about 50 columns (type of data) and about 300 intake calls per year.
They use this data to determine what needs the survivor has (eg, shelter for night, etc.).  Therefore this data needs to be seen by the intake volunteer and others, internally, almost immediately (eg, they need to sometime make a call back within 15-20 mins).
For data they would receive via web form, they would NOT need to verify or validate the data.  
For reporting, they report to the national organization quarterly and annually.
The national data is different from local data (we will find out how different).  
Internally, the intake person(s) would need to see the data almost immediately (to be able to call back, help, etc.)
Internally, the grant writer will have to manipulate the data, but does not need the latest data immediately.   She would like to be able to sort a spreadsheet by date, by types of violence, and judicial district. 
There wil have to be fields for "ignore" (if a troll) 

Thinking about the intake form, we will have to show ot user (survivor) a review, , opportunity to edit and then submit.
we don;t have to worry about duplicates (they do not now).

They have a written out process for the whole intake process.

We are getting some info from Owner (lynne):
1) Intake form
2) Present google spreadsheet form and data types
3) national google spreadsheet and datatypes
4) where is the web site data stored (in drupel)?

**Comment by biodavis** [comment]
Data in their "database" (Google spreadsheet) as well as the data they need to submit to National Org is at:   https://drive.google.com/open?id=0B5abWC3UPlExflRYUWVlcWU5OWtsUTZodF92S3VJcVAxYWdvWWZjM2c0c3JCc0VvNEh2N2c&authuser=0

**Comment by biodavis** [comment]
added the INTAKE form (as PDF to same folder, above.  @karen and @drosile, please examine to see it done with this task
