### ISSUE TITLE
Documentation for creating reports 

### ISSUE THREAD

**Issue by hasuf** [codefordenver/sol-cavp#86]
Based on work by Stacy, IntakeDataSample: https://drive.google.com/folderview?id=0B-gcSX6p7xVPfmV5WFFUOHg3c2RYQzA2bEpXUHE1RWNlTlJtQWR1Z3JJVzR4NjNFQnFjbHM&usp=sharing

We need documentation for SOL/CAVP's Development Director (possibly combined with a training session)

**Comment by hasuf** [comment]
See also: #85

**Comment by switzersc** [comment]
Purpose: document ways to visualize data collected from forms to make reporting to national org and formatting data for internal use, etc.
